server:
  port: 9002

mybatis:
  type-aliases-package: com.springcloud.api.entity
  mapper-locations: classpath:mapper/**.xml

spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.78.101:3306/cloudDB02
    username: root
    password: Fei130823.
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: provider-9002  #实例名称
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: microservicecloud-provider
  company.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$