server: 
  port: 1001
 
spring: 
  application:
    name: microservicecloud-zuul
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: zuul-1001.com
    prefer-ip-address: true 
 
 
zuul:
#  ignored-services: microservicecloud-dept
  prefix: /linyf #不能用zuul 不好使
  ignored-services: "*" #禁止通过所有实例名访问
  routes:
    myroute1:
      serviceId: microservicecloud-dept
      path: /mydept/**
 
info:
  app.name: microservicecloud-provider
  company.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

